# Set the base image to the official Node.js image
FROM node:20 as build

# Create a working directory for the app
WORKDIR /app

# Copy the package.json and package-lock.json files to the working directory
COPY package*.json ./
COPY index.html ./

# So we can run tests
COPY __tests__ ./__tests__
COPY jest.config.js ./

# Install dependencies using npm
RUN npm install
