version: "3.8"
services:
  wca_registration_handler:
    container_name: wca_registration_handler
    build:
      context: .
      dockerfile: dockerfile.dev
    ports:
      - "3001:3000"
    environment:
      LOCALSTACK_ENDPOINT: "http://localstack:4566"
      AWS_REGION: "us-east-1"
      AWS_ACCESS_KEY_ID: "fake-key"
      AWS_SECRET_ACCESS_KEY: "fake-access-key"
      VAULT_ADDR: "http://wca_vault:8200"
      VAULT_DEV_ROOT_TOKEN_ID: aDGdUASDGIUASGDKI
      PROMETHEUS_EXPORTER: "prometheus_exporter"
      REDIS_URL: "redis://redis:6379"
    volumes:
      - .:/app
      - gems_volume_handler:/usr/local/bundle
    tty: true
    # First, install Ruby and Node dependencies
    # Start the server and bind to 0.0.0.0 (vs 127.0.0.1) so Docker's port mappings work correctly
    command: >
      bash -c 'bundle install && yarn install && bin/rake db:seed &&
      bin/rails server -b 0.0.0.0'
    networks:
      - wca-registration
    depends_on:
      - localstack
      - wca_vault
      - prometheus_exporter
      - redis

  prometheus_exporter:
    container_name: prometheus_exporter
    build:
      context: .
      dockerfile: dockerfile.metrics
    tty: true
    ports:
      - "9091:9091"
    networks:
      - wca-registration


  wca_registration_worker:
    container_name: wca_registration_worker
    build:
      context: .
      dockerfile: dockerfile.dev
    environment:
      LOCALSTACK_ENDPOINT: "http://localstack:4566"
      AWS_REGION: "us-east-1"
      AWS_ACCESS_KEY_ID: "fake-key"
      AWS_SECRET_ACCESS_KEY: "fake-access-key"
      PROMETHEUS_EXPORTER: "prometheus_exporter"

    volumes:
      - .:/app
      - gems_volume_worker:/usr/local/bundle
    tty: true
    # First, install Ruby and Node dependencies
    # Start the server and bind to 0.0.0.0 (vs 127.0.0.1) so Docker's port mappings work correctly
    command: >
      bash -c 'bundle install &&
      while ! curl http://wca_registration_handler:3000/healthcheck >/dev/null 2>&1; do
              echo "Waiting for Handler to be ready" && sleep 5 ;
            done && ruby -r "/app/app/worker/queue_poller.rb" -e "QueuePoller.perform"'
    networks:
      - wca-registration
    depends_on:
      - wca_registration_handler

  # Emulate AWS Services Locally
  localstack:
    container_name: "localstack"
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      - DEBUG=${DEBUG-}
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "./localstack/volume:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - wca-registration

  dynamodb-admin:
    container_name: dynamodb-admin
    image: aaronshaf/dynamodb-admin
    ports:
      - "8001:8001"
    environment:
      DYNAMO_ENDPOINT: "http://localstack:4566"
      AWS_REGION: "us-east-1"
      AWS_ACCESS_KEY_ID: my_cool_key
      AWS_SECRET_ACCESS_KEY: my_cool_secret
    depends_on:
      - localstack
    networks:
      - wca-registration

  wca_vault:
    container_name: vault
    image: hashicorp/vault
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=aDGdUASDGIUASGDKI
    ports:
      - "8200:8200"
    networks:
      - wca-registration

  # Frontend
  frontend:
    container_name: frontend
    build:
      context: Frontend
    tty:
      true
    command: bash -c "npm run watch"
    networks:
      - wca-registration
    volumes:
      - ./Frontend/src:/app/src

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "3002:80"
    networks:
      - wca-registration
    volumes:
      - ./Frontend/frontend_local.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - '6379:6379'
    volumes:
      - cache:/data

volumes:
  gems_volume_handler:
    driver: local
  gems_volume_worker:
    driver: local
  cache:
    driver: local


networks:
  wca-registration:
    name: wca-registration
