version: "3.8"
services:
  wca_registration:
    build:
      context: .
      dockerfile: dockerfile.dev
    ports:
      - "3001:3000"
    environment:
      LOCALSTACK_ENDPOINT: "http://localstack:4566"
    volumes:
      - .:/app
      - gems_volume:/usr/local/bundle
    tty: true
    # First, install Ruby and Node dependencies
    # Start the server and bind to 0.0.0.0 (vs 127.0.0.1) so Docker's port mappings work correctly
    command: >
      bash -c 'bundle install && yarn install && bin/rake db:seed &&
      bin/rails server -b 0.0.0.0'
    networks:
      - wca-registration
    depends_on:
      - localstack

  # Emulate AWS Services Locally
  localstack:
    container_name: "localstack"
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      - DEBUG=${DEBUG-}
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "./localstack/volume:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - wca-registration

volumes:
  gems_volume:
    driver: local

networks:
  wca-registration:
    name: wca-registration
