version: "3.8"
services:
  wca_registration:
    build:
      context: .
      dockerfile: dockerfile.dev
    ports:
      - "3001:3000"
    environment:
      WCA_MAIN: test
    volumes:
      - .:/app
      - gems_volume:/usr/local/bundle
    tty: true
    # First, install Ruby and Node dependencies
    # Start the server and bind to 0.0.0.0 (vs 127.0.0.1) so Docker's port mappings work correctly
    command: >
      bash -c 'bundle install && yarn install &&
      bin/rails server -b 0.0.0.0'
    networks:
      - wca-registration

volumes:
  gems_volume:
    driver: local

networks:
  wca-registration:
    name: wca-registration
