import { EventId } from '@wca/helpers'

// These will be generated by the swagger file generated with Rswag
interface SubmitRegistrationBody {
  competitor_id: string
  competition_id: string
  event_ids: EventId[]
}

interface UpdateRegistrationBody {
  competitor_id: string
  competition_id: string
  status: string
}

type GetRegistrationBody = Record<string, never>

interface DeleteRegistrationBody {
  competitor_id: string
  competition_id: string
}
