import { EventId } from '@wca/helpers'

// These will be generated by the swagger file generated with Rswag
interface SubmitRegistrationBody {
  user_id: string
  competition_id: string
  comment: string
  event_ids: EventId[]
}

interface UpdateRegistrationBody {
  user_id: string
  competition_id: string
  status?: string
  event_ids?: EventId[]
  comment?: string
}

type GetRegistrationBody = Record<string, never>

interface ErrorResponse {
  error: string
  statusCode: number
}

export interface UserType {
  id: string
  authToken?: string
}
