// These will be generated by the swagger file generated with Rswag
type WCAEvent =
  | '222'
  | '333'
  | '333bf'
  | '333fm'
  | '333mbf'
  | '333ft'
  | '333oh'
  | '444'
  | '444bf'
  | '555'
  | '555bf'
  | '666'
  | '777'
  | 'clock'
  | 'magic'
  | 'minx'
  | 'mmagic'
  | 'pyram'
  | 'skewb'
  | 'sq1'

interface SubmitRegistrationBody {
  competitor_id: string
  competition_id: string
  event_ids: WCAEvent[]
}

interface UpdateRegistrationBody {
  competitor_id: string
  competition_id: string
  status: string
}

type GetRegistrationBody = Record<string, never>

interface DeleteRegistrationBody {
  competitor_id: string
  competition_id: string
}
