# frozen_string_literal: true


module ErrorCodes
  # System Errors
  INVALID_TOKEN = -1
  EXPIRED_TOKEN = -2
  MISSING_AUTHENTICATION = -3

  # Competition Errors
  COMPETITION_NOT_FOUND = -1000
  COMPETITION_API_5XX = -1001
  COMPETITION_CLOSED = -1002
  COMPETITION_INVALID_EVENTS = -1003

  # User Errors
  USER_IMPERSONATION = -2000
  USER_IS_BANNED = -2001
  USER_PROFILE_INCOMPLETE = -2002
  USER_INSUFFICIENT_PERMISSIONS = -2003
end
