name: Test

on:
  pull_request:
    branches: main

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      RACK_ENV: test
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby # Only install ruby to get Rubocop
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.2'
      - name: Lint with Rubocop
        run: |
          gem install rubocop
          rubocop
      - name: Lint with Eslint
        run: |
          cd ./Frontend
          npm install
          npm run lint
      - name: Backend Tests
        run: docker compose -f "docker-compose.backend-test.yml" up wca_registration_handler --abort-on-container-exit
      - name: Frontend Tests
        run: docker compose -f "docker-compose.frontend-test.yml" up cypress --abort-on-container-exit
