name: Test

on:
  pull_request:
    branches: main

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      RACK_ENV: test
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby # Only install ruby to get Rubocop
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Lint with Rubocop
        run: |
          bundle exec rubocop
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: pre-build images for caching
        uses: docker/bake-action@v4
        with:
          load: true
          files: |
            docker-compose.backend-test.yml
          set: |
            *.cache-to=type=gha,mode=max                                                                                
            *.cache-from=type=gha
      - name: Backend Tests
        run: docker compose -f "docker-compose.backend-test.yml" run wca_registration_test bash -c 'bundle install && yarn install && bin/rake db:seed && RAILS_ENV=test bundle exec rspec --exclude-pattern spec/cache'
      - name: Contract Test
        run: docker compose -f "docker-compose.contract-test.yml" run frontend bash -c 'npm run test:contract'
